### ISSUE TITLE
Add pipe as backend/mixer

### ISSUE THREAD

**Issue by Schluggi** [librespot-org/librespot-java#121]
**Is your feature request related to a problem? Please describe.**
I'm using [snapcast](https://github.com/badaix/snapcast) to play Spotify synchrony in every room. Now i want to switch from `librespot` to `librespot-java` but `pipe` is not available as backend/mixer.

**Describe the solution you'd like**
Please add the pipe as backend/mixer and may rename "mixers" to "backends" because `pipe` is not a mixer.

**Describe alternatives you've considered**
Maybe there is an other option `librespot-java` can interact with the [snapserver](https://github.com/badaix/snapcast) but I have not found one jet.

**Additional context**
_Empty_

Big thanks to you and this Project. I hope we find a solution.

**Comment by devgianlu** [comment]
I've implemented this into `crossfade-support` (#120), you can check it out there. Let me know if there's any issue.

**Comment by devgianlu** [comment]
Better to discuss here the issue you're having.

I've just tested it with your configuration and for me the delay isn't that evidente. Almost instant.

**Comment by Schluggi** [comment]
Interesting. I've just compile the current branch again on my laptop (previously on RPI 3B+) with still the same result. The delay is insane and I've a lot of notice a nothing thing: If i pause at 30seconds and waiting for 10 seconds librespot shows it
```
2019-08-07 22:03:57 DEBUG Player:116 - Received command: Pause
2019-08-07 22:03:57 INFO  DeviceStateHandler:156 - Updated state. {reason: PLAYER_STATE_CHANGED}
```
but if i press play again, the progress bar jumps to 40 seconds as if the song had been played in the background.

BTW: Can you add the option to pipe into stdout ? 

Maybe offtopic: Meanwhile I've some exceptions:
```
2019-08-07 21:56:17 TRACE CdnManager:261 - Chunk 92/94 completed, cdn: audio-sp-fra2.pscdn.co, cached: false, stream: {fileId: 455FC7082CE7F71DD4F1901FF79D450F9D305D63}
2019-08-07 21:56:17 TRACE CdnManager:261 - Chunk 93/94 completed, cdn: audio-sp-fra2.pscdn.co, cached: false, stream: {fileId: 455FC7082CE7F71DD4F1901FF79D450F9D305D63}
2019-08-07 21:56:17 INFO  Player:276 - Crossfading to next track.
2019-08-07 21:56:17 TRACE Player:246 - End of track. Proceeding with next.
2019-08-07 21:56:17 WARN  Player:197 - Couldn't update track duration!
Exception in thread "player-runner-writer-443833373" java.lang.NullPointerException
	at xyz.gianlu.librespot.player.PlayerRunner$TrackHandler.time(PlayerRunner.java:580)
	at xyz.gianlu.librespot.player.Player.loadTrack(Player.java:344)
	at xyz.gianlu.librespot.player.Player.handleNext(Player.java:423)
	at xyz.gianlu.librespot.player.Player.endOfTrack(Player.java:247)
	at xyz.gianlu.librespot.player.PlayerRunner$TrackHandler.run(PlayerRunner.java:656)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-08-07 21:56:17 TRACE CdnManager:261 - Chunk 0/107 completed, cdn: audio4-fa.scdn.co, cached: false, stream: {fileId: A6D6E11A8AF8A2D179A04FDA3BF4FF14B3083073}
2019-08-07 21:56:17 TRACE NormalizationData:29 - Loaded normalization data, track_gain: 3,11, track_peak: 0,52, album_gain: 2,63, album_peak: 0,87
2019-08-07 21:56:17 INFO  PlayerRunner:491 - Loaded track, name: 'Nuvole Bianche', artists: 'Ludovico Einaudi', gid: 73A7CDCBC27E4E268E6817DE40BBF1CD
2019-08-07 21:56:17 TRACE PlayerRunner:514 - Loaded codec (VORBIS), fileId: {fileId: A6D6E11A8AF8A2D179A04FDA3BF4FF14B3083073}, format: PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian
2019-08-07 21:56:17 TRACE CdnManager:261 - Chunk 0/107 completed, cdn: audio4-fa.scdn.co, cached: false, stream: {fileId: A6D6E11A8AF8A2D179A04FDA3BF4FF14B3083073}
2019-08-07 21:56:17 TRACE CdnManager:261 - Chunk 2/107 completed, cdn: audio4-fa.scdn.co, cached: false, stream: {fileId: A6D6E11A8AF8A2D179A04FDA3BF4FF14B3083073}
2019-08-07 21:56:17 INFO  DeviceStateHandler:156 - Updated state. {reason: PLAYER_STATE_CHANGED}
2019-08-07 21:56:17 TRACE MixingLine:164 - Toggle second channel: true
2019-08-07 21:56:17 TRACE MixingLine:124 - Toggle first channel: false
Exception in thread "player-runner-790368407" java.lang.NullPointerException
	at xyz.gianlu.librespot.player.mixing.MixingLine.read(MixingLine.java:64)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at xyz.gianlu.librespot.player.PlayerRunner.run(PlayerRunner.java:124)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-08-07 21:56:17 TRACE CdnManager:261 - Chunk 3/107 completed, cdn: audio4-fa.scdn.co, cached: false, stream: {fileId: A6D6E11A8AF8A2D179A04FDA3BF4FF14B3083073}
2019-08-07 21:56:17 TRACE CdnManager:261 - Chunk 1/107 completed, cdn: audio4-fa.scdn.co, cached: false, stream: {fileId: A6D6E11A8AF8A2D179A04FDA3BF4FF14B3083073}
2019-08-07 21:56:37 WARN  Session:755 - Socket timed out. Reconnecting...
[..]
019-08-07 22:01:52 DEBUG Player:116 - Received command: SkipNext
2019-08-07 22:01:52 TRACE MixingLine:164 - Toggle second channel: false
Exception in thread "player-runner-writer-728477902" java.lang.NullPointerException
	at com.jcraft.jogg.StreamState.packetout(StreamState.java:186)
	at xyz.gianlu.librespot.player.codecs.VorbisCodec.readSome(VorbisCodec.java:139)
	at xyz.gianlu.librespot.player.PlayerRunner$TrackHandler.run(PlayerRunner.java:655)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-08-07 22:01:52 INFO  DeviceStateHandler:156 - Updated state. {reason: PLAYER_STATE_CHANGED}
2019-08-07 22:01:52 INFO  DeviceStateHandler:156 - Updated state. {reason: PLAYER_STATE_CHANGED}
2019-08-07 22:01:52 FATAL Player:224 - Can't load track (content restricted), gid: 90A7FED88990497CA5504A52DCF7AAF4
xyz.gianlu.librespot.player.ContentRestrictedException
	at xyz.gianlu.librespot.player.ContentRestrictedException.checkRestrictions(ContentRestrictedException.java:16)
	at xyz.gianlu.librespot.player.feeders.PlayableContentFeeder.loadTrack(PlayableContentFeeder.java:80)
	at xyz.gianlu.librespot.player.feeders.PlayableContentFeeder.load(PlayableContentFeeder.java:58)
	at xyz.gianlu.librespot.player.PlayerRunner$TrackHandler.load(PlayerRunner.java:481)
	at xyz.gianlu.librespot.player.PlayerRunner$TrackHandler.access$1000(PlayerRunner.java:433)
	at xyz.gianlu.librespot.player.PlayerRunner$Looper.run(PlayerRunner.java:377)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-08-07 22:01:52 INFO  DeviceStateHandler:156 - Updated state. {reason: PLAYER_STATE_CHANGED}
2019-08-07 22:01:52 TRACE MixingLine:124 - Toggle first channel: true
2019-08-07 22:01:52 TRACE MixingLine:124 - Toggle first channel: false
Exception in thread "player-runner-looper-1975053916" java.lang.NullPointerException
	at xyz.gianlu.librespot.player.PlayerRunner$TrackHandler.close(PlayerRunner.java:562)
	at xyz.gianlu.librespot.player.PlayerRunner$Looper.run(PlayerRunner.java:400)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "player-runner-writer-456366527" java.lang.NullPointerException
	at xyz.gianlu.librespot.player.PlayerRunner$TrackHandler.shouldCrossfade(PlayerRunner.java:605)
	at xyz.gianlu.librespot.player.PlayerRunner$TrackHandler.run(PlayerRunner.java:651)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-08-07 22:02:12 TRACE Session:761 - Handled Ping {payload: 5D4B2E44}

```

**Comment by devgianlu** [comment]
I should have got rid of the exception now at least.

I'm too experiencing the issue with pausing.

Don't know if outputting to stdout is good idea, the logs output needs to be moved to stderr.

**Comment by Schluggi** [comment]
Nice work :)

Does 28b39a2 fixed it?

Maybe you could add a loglevel option to filter the output and disable logging to stdout?

**Comment by devgianlu** [comment]
I've fixed some issue, I'm testing just now a synchronization exception. Should be ready in couple of minutes. I've added an option to ouput to stdout, to make it work, you need to edit `core/src/main/resources/log4j.properties` and change `stdout` with `stderr`.

The pausing thing is yet to be fixed.

**Comment by Schluggi** [comment]
If i do so and set `output="STDOUT"` i've got this error:

```
Exception in thread "zeroconf-client-1180557794" java.lang.IllegalArgumentException: Unknown output: STDOUT
	at xyz.gianlu.librespot.player.PlayerRunner.<init>(PlayerRunner.java:85)
	at xyz.gianlu.librespot.player.Player.<init>(Player.java:47)
	at xyz.gianlu.librespot.core.Session.authenticate(Session.java:269)
	at xyz.gianlu.librespot.core.ZeroconfServer.handleAddUser(ZeroconfServer.java:315)
	at xyz.gianlu.librespot.core.ZeroconfServer.access$100(ZeroconfServer.java:35)
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:412)
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:348)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by devgianlu** [comment]
Was missing a `break;`...

**Comment by Schluggi** [comment]
> I'm too experiencing the issue with pausing.

I think is kind of fixed. I paused at 10seconds, wait 5seconds and press play. Now the process bar jumps to 15seconds and than back to 10seconds. And when the first jump is part of the next song, the next song will started at the beginning. Little confusing ;)

**Comment by devgianlu** [comment]
Same for me (on Android, what are you using?). Looks like the client doesn't fully acknowledge that it is in a paused state.

**Comment by Schluggi** [comment]
I'm using Android (9) too. Spotify version 8.5.17.676.

**Comment by devgianlu** [comment]
How does snapcast handles the volume? Currently if the pipe option is used, changing the volume on Spotify won't do anything. I think that should be fixed.

**Comment by Schluggi** [comment]
Isn't the spotify volume part of the piped output? Snapcast do not interact with the Spotify volume as far as I know. There is an extra volume control from snapcast, but this does not change my spotify volume. So for max volume i've to change it in spotify and snapcast.

**Comment by devgianlu** [comment]
Therefore, Spotify volume should change the pipe one for it to work properly?

**Comment by Schluggi** [comment]
Exact! :)

**Comment by devgianlu** [comment]
I've made some changes to `new-spotify-api`, should work now.

**Comment by devgianlu** [comment]
After some research I discovered that pipes have a buffer which is what is consumed when you've already paused the track. Try executing the following command to see how many bytes the pipe can hold:

```bash
cat /proc/sys/fs/pipe-max-size
```

The pipe size can be adjusted (I didn't try that) by editing the said file. [Source](https://unix.stackexchange.com/questions/11946/how-big-is-the-pipe-buffer)
